### ISSUE TITLE
app crash on Login 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6819]
Apparently because of this

```
FATAL EXCEPTION: pool-9-thread-1
                                                                                                    Process: io.hexawallet.hexa.development, PID: 10220
                                                                                                    java.lang.IllegalArgumentException: TcpSocketsNo socket with id 0
                                                                                                    	at com.asterinet.react.tcpsocket.TcpSocketModule.getTcpClient(TcpSocketModule.java:263)
                                                                                                    	at com.asterinet.react.tcpsocket.TcpSocketModule.access$700(TcpSocketModule.java:28)
                                                                                                    	at com.asterinet.react.tcpsocket.TcpSocketModule$2.run(TcpSocketModule.java:106)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by cakesoft-vijaysingh** [comment]
This issue is most probably related to react-native-tcp-socket lib version. https://github.com/Rapsssito/react-native-tcp-socket/issues/167 
raised pr for updating it

**Comment by Deveshshankar** [comment]
Verified on 2.3.0 (619)
